name: Build FFmpeg.wasm
on:
  push:
    branches:
      - n4.3.1-wasm
    tags:
      - v*
  pull_request:
    branches:
      - n4.3.1-wasm

env:
  FFMPEG_ST: no
  PUBLISH_PATH: wasm/packages/core
  DIST_PATH: wasm/packages/core/dist
  CACHE_KEY_PREFIX: ffmpeg.wasm-core
  # EM_VERSION: 2.0.8
  # EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get commit hash
        id: get-commit-hash
        run: |
          echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      - name: Cache multiple paths
        uses: actions/cache@v2
        env:
          GIT_HASH: $(git rev-parse --short HEAD)
        with:
          path: |
            build
            wasm/cache
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ steps.get-commit-hash.outputs.hash }}-ffmpeg
          restore-keys: |
            ${{ env.CACHE_KEY_PREFIX }}-${{ steps.get-commit-hash.outputs.hash }}-
      - name: List cached libs
        run: ls -R build || true
      - name: Build FFMpeg
        run: |
          bash build-with-docker.sh \
            install-deps \
            configure-ffmpeg \
            build-ffmpeg
      - uses: actions/upload-artifact@master
        with:
          name: ffmpeg-core
          path: ${{ env.DIST_PATH }}
      - uses: actions/setup-node@v3
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@blueberrymuffin3'
      - run: npm ci
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        working-directory: ${{ env.PUBLISH_PATH }}
      - run: npm publish --access public
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        working-directory: ${{ env.PUBLISH_PATH }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    